name: Build

on: 
  create:
    tags:
      - v*

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get Release
      id: get
      uses: bruceadams/get-release@v1.2.0

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: sources/repo

    - name: Create sources tarball
      run: |
        tar -C sources -zcvf repo.tar.gz repo
        zip -r -9 sources.zip repo/sources

    - name: Upload tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get.outputs.upload_url }}
        asset_path: ./repo.tar.gz
        asset_name: repo.tar.gz
        asset_content_type: application/gzip

    - name: Upload zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get.outputs.upload_url }}
        asset_path: ./repo.zip
        asset_name: repo.zip
        asset_content_type: application/zip
