name: Build

on: 
  release:
    types:
      - created

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get Release
      id: get
      uses: bruceadams/get-release@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_REF }}
        submodules: recursive
        path: sources/repo

    - name: Create sources tarball
      run: |
        tar --exclude-vcs -C sources -zcvf repo.tar.gz repo
        zip -9 -x \*.git\* -r repo.zip sources/repo

    - name: Upload tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get.outputs.upload_url }}
        asset_path: ./repo.tar.gz
        asset_name: repo.tar.gz
        asset_content_type: application/gzip

    - name: Upload zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get.outputs.upload_url }}
        asset_path: ./repo.zip
        asset_name: repo.zip
        asset_content_type: application/zip
